add missing plugins
openmediavault/openmediavault-docs pull request #69
Opened 2020-12-23 13:45 UTC by mi-hol

2020-12-23 20:18 UTC, flmaxey approved these changes

2020-12-24 17:17 UTC, votdev approved these changes
LGTM, except my comment.

2020-12-24 17:17 UTC, votdev commented on plugins.rst
> +* **ShAirPort**: Provides Airtunes emulator. Stream music wirelessly to your iPod/iPad/iPhone/iTunes.
I'm not sure, but i think it is named `Shairport`, at least according to the [Git repository](https://github.com/mikebrady/shairport-sync) of the project.

2021-04-03 11:34 UTC, votdev approved these changes

2021-04-03 11:39 UTC, votdev requested changes

2021-04-03 11:39 UTC, votdev commented on plugins.rst
> +* **Diskstats**: Complementary plugin to extend system statistics collection by adding iostats graphs.
Could you please change that to the following. I think this phrasing is more clear than the original (moved) text.
```suggestion
* **Diskstats**: Complementary plugin to extend system statistics collection by adding I/O statistic graphs.
```

2021-04-03 11:39 UTC, votdev commented on plugins.rst
> +* **ShareRootFs**: Provides shared directires on root file sstem
```suggestion
* **ShareRootFs**: Provides shared directories on root file system.
```

2021-04-03 11:39 UTC, votdev commented on plugins.rst
> +* **SNMP**: Provides Simple Network Management Protocol (SNMP). SNMP is an Internet Standard protocol for collecting and organizing information about managed devices on IP networks
Most enumerations end with a dot, so we should do the same here.
```suggestion
* **SNMP**: Provides Simple Network Management Protocol (SNMP). SNMP is an Internet Standard protocol for collecting and organizing information about managed devices on IP networks.
```

2021-04-03 11:39 UTC, votdev commented on plugins.rst
> +* **TFtp**: Provides Trivial File Transfer Protocol (TFTP). TFTP is a simple lockstep File Transfer Protocol which allows a client to get a file from or put a file onto a remote host
```suggestion
* **TFtp**: Provides Trivial File Transfer Protocol (TFTP). TFTP is a simple lockstep File Transfer Protocol which allows a client to get a file from or put a file onto a remote host.
```

2021-04-03 13:53 UTC, votdev requested changes

2021-04-03 13:53 UTC, votdev commented on plugins.rst
> +* **ShareRootFs**: Provides shared directires on root file sstem
This issue hasn't been fixed.

2021-04-03 16:40 UTC, mi-hol commented
weird, I had pressed "commit suggestion" as flagged by github in below screenshot, but the changes was actually not applied by github :(
I'd suggest to merge as the typo existed before I added line and to fix them in a second PR

![image](https://user-images.githubusercontent.com/22799428/113484953-6208e280-94ab-11eb-8c8f-4d273d79d194.png)

2021-04-03 17:16 UTC, mi-hol commented
after a page refresh, I was able to accept the change again, weird (as written)

2021-04-06 18:50 UTC, merged