chore: add China mirroring service section
openmediavault/openmediavault-docs pull request #90
Opened 2021-08-06 13:21 UTC by septs

CC @ZenithalHourlyRate

2021-08-08 15:47 UTC, septs commented
CC @votdev

2021-08-09 09:48 UTC, votdev commented on installation/on_debian.rst
> +If you are a user in mainland China, TUNA provides mirroring services.
```suggestion
If you are a user in mainland China, TUNA provides `mirroring services <https://mirrors.tuna.tsinghua.edu.cn/help/openmediavault/>`_.
```

2021-08-09 09:48 UTC, votdev requested changes

2021-08-09 09:48 UTC, votdev commented on installation/on_debian.rst
> +Please see <https://mirrors.tuna.tsinghua.edu.cn/help/openmediavault/>
Remove this line.

2021-08-09 12:17 UTC, votdev requested changes

2021-08-09 12:17 UTC, votdev commented on installation/on_debian.rst
> +If you are a user in mainland China, TUNA provides `mirroring services <https://mirrors.tuna.tsinghua.edu.cn/help/openmediavault/>`.
The `_` is missing which will result in a render error.
```suggestion
If you are a user in mainland China, TUNA provides `mirroring services <https://mirrors.tuna.tsinghua.edu.cn/help/openmediavault/>`_.
```

2021-08-09 12:41 UTC, votdev commented
Thanks for the origin PR. Superseded by 1b9fe3eb2f4bdca327dc3969d505e7ef6c02d6c5.

2021-08-09 12:41 UTC, closed without merging